var tableauQuestion = [
    {   question : "Du fährst 65 kmh. Du kommst in eine Wohngegend. Was tust du?",
        propositionA : "Beschleunigen",
        propositionB : "So weiterfahren, solange keine anderen Fahrzeuge zu sehen sind",
        propositionC : "Abbremsen",
        propositionD : "So weiterfahren.",
        reponse : "C"},

    {   question : "Was tust du, wenn bei einem Abbiegevorgang ein Fußgänger deinen Weg kreuzt:",
        propositionA : "Den Fußgänger umfahren",
        propositionB : "Erst fahren, wenn alle anderen Fahrzeuge fort sind",
        propositionC : "Warten, bis der Fußgänger vorbei gegangen ist",
        propositionD : "Dem Fußgänger in die Fresse schießen und weiterfahren",
        reponse : "C"},

    {   question : "Wie schnell darfst du in einer Wohngegend fahren: __ kmh",
        propositionA : "40",
        propositionB : "45",
        propositionC : "50",
        propositionD : "55",
        reponse : "C"},

  {   question : "Wenn du die Fahrspur wechseln willst, dann tust du:",
        propositionA : "In den Rückspiegel schauen",
        propositionB : "Die \"Blindspots\" abchecken",
        propositionC : "Den Blinker setzen",
        propositionD : "Alles, was hier steht",
        reponse : "D"},

  {   question : "Ab wv Promille zählst du als alkoholisierter Fahrer?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "Wann darfst du an einer Ampel fahren?",
        propositionA : "Wenn sie grün ist",
        propositionB : "Wenn sonst keiner da ist",
        propositionC : "Wenn eine Schule in der Nähe ist",
        propositionD : "Wenn sie grün ist / oder rot, du aber rechts abbiegen willst",
        reponse : "D"},

  {   question : "Ein Fußgänger steht bei roter Ampel. Was tust du?",
        propositionA : "Du lässt den Fußgänger vorbei.",
        propositionB : "Du schaust ihm zu, bis du weiterfahren kannst.",
        propositionC : "Du winkst ihm zu, damit er rüber geht.",
        propositionD : "Du fährst weiter, weil du grün hast.",
        reponse : "D"},

  {   question : "Was ist erlaubt, wenn du jemanden überholst?",
        propositionA : "Ganz dicht auffahren, um den Überholvorgang schnell zu beenden.",
        propositionB : "Überholen, ohne die Fahrbahn zu verlassen.",
        propositionC : "Auf der anderen Straßenseite fahren.",
        propositionD : "Schneller als erlaubt fahren.",
        reponse : "C"},

  {   question : "Du fährst auf der Autobahn. Die Beschilderung sagt maximal 120 kmh. Fast alle anderen fahren aber 140 kmh. Wie schnell fährst du?",
        propositionA : "90 kmh",
        propositionB : "120 kmh",
        propositionC : "140 kmh",
        propositionD : "210 kmh",
        reponse : "B"},

  {   question : "Wenn du von einem anderen Fahrzeug überholt wirst tust du das folgende auf keinen Fall:",
        propositionA : "Langsamer werden",
        propositionB : "In die Spiegel gucken",
        propositionC : "Anderen beim Fahren zusehen",
        propositionD : "Schneller fahren",
        reponse : "D"},

  {   question : "Ein Wagen kommt von hinten mit Blaulicht und Sirene. Was tust du?",
        propositionA : "Rechts ran fahren und den Bastard mit dem RPG hochjagen.",
        propositionB : "Rechts ran fahren bzw. eine Rettungsgasse bilden.",
        propositionC : "Mitten auf der Straße halten.",
        propositionD : "Den Verantwortlichen Wagen von der Straße drängen.",
        reponse : "B"},
]
